# Generated by Django 4.0.3 on 2022-07-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_username_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='default/profile.png', upload_to='profile/'),
        ),
    ]
