# Generated by Django 4.0.3 on 2022-07-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0005_remove_brestcancertext_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LungCancerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan', models.FileField(upload_to='lung-cancer/')),
            ],
        ),
    ]
