# Generated by Django 4.0.3 on 2022-07-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LungCancerText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('True', 'Male'), ('False', 'Female')], max_length=255)),
                ('age', models.IntegerField()),
                ('smoking', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=255)),
                ('yellow_fingers', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=255)),
                ('anxiety', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=255)),
                ('peer_pressure', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=255)),
                ('chronic_disease', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=255)),
                ('fatigue', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=255)),
                ('allergy', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=255)),
                ('wheezing', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=255)),
                ('alcohol_consumption', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=255)),
                ('coughing', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=255)),
                ('shortness_of_breadth', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=255)),
                ('swallowing_difficulty', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=255)),
                ('chest_pain', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LungReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cancer.lungcancertext')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
    ]
