# Generated by Django 4.0.3 on 2022-07-16 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_profile_pic'),
        ('cancer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrestCancerText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.IntegerField()),
                ('smoking', models.CharField(choices=[('1.0', 'Yes'), ('0.0', 'No')], max_length=255)),
                ('alcohol', models.CharField(choices=[('1.0', 'Yes'), ('0.0', 'No')], max_length=255)),
                ('stroke', models.CharField(choices=[('1.0', 'Yes'), ('0.0', 'No')], max_length=255)),
                ('mental_heath', models.CharField(choices=[('1.0', 'Yes'), ('0.0', 'No')], max_length=255)),
                ('diff_walking', models.CharField(choices=[('1.0', 'Yes'), ('0.0', 'No')], max_length=255)),
                ('gender', models.CharField(choices=[('True', 'Male'), ('False', 'Female')], max_length=255)),
                ('age_category', models.DecimalField(decimal_places=3, max_digits=5)),
                ('race', models.DecimalField(decimal_places=3, max_digits=5)),
                ('physical_health', models.DecimalField(decimal_places=3, max_digits=5)),
                ('diabetic', models.DecimalField(decimal_places=3, max_digits=5)),
                ('GenHealth', models.DecimalField(decimal_places=3, max_digits=5)),
                ('SleepTime', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Asthma', models.DecimalField(decimal_places=3, max_digits=5)),
                ('kidney_disease', models.DecimalField(decimal_places=3, max_digits=5)),
                ('skin_cancer', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='BrestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cancer.brestcancertext')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
    ]
