# Generated by Django 4.0.3 on 2022-07-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0002_brestcancertext_brestreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brestcancertext',
            name='bmi',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
