# Generated by Django 4.0.3 on 2022-07-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0002_alter_brestcancertext_area_mean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brestcancertext',
            name='area_mean',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='area_se',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='area_worst',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='compactness_mean',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='compactness_se',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='compactness_worst',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='concave_points_mean',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='concave_points_se',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='concave_points_worst',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='concavity_mean',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='concavity_se',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='concavity_worst',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='fractal_dimension_mean',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='fractal_dimension_se',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='fractal_dimension_worst',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='perimeter_mean',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='perimeter_se',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='perimeter_worst',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='radius_mean',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='radius_se',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='radius_worst',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='smoothness_mean',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='smoothness_se',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='smoothness_worst',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='symmetry_mean',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='symmetry_se',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='symmetry_worst',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='texture_mean',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='texture_se',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
        migrations.AlterField(
            model_name='brestcancertext',
            name='texture_worst',
            field=models.DecimalField(decimal_places=255, max_digits=255),
        ),
    ]
