# Generated by Django 4.0.3 on 2022-07-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0003_alter_brestcancertext_bmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brestreport',
            name='data',
        ),
        migrations.RemoveField(
            model_name='brestreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='BrestCancerText',
        ),
        migrations.DeleteModel(
            name='BrestReport',
        ),
    ]
