# Generated by Django 4.0.3 on 2022-07-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0004_alter_brestcancertext_area_mean_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brestcancertext',
            name='user',
        ),
    ]
