# Generated by Django 4.0.3 on 2022-07-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0006_lungcancerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lungreport',
            name='data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cancer.lungcancertext'),
        ),
    ]
