# Generated by Django 4.0.3 on 2022-07-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyereport',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
