# Generated by Django 4.0.3 on 2022-07-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartcancertext',
            name='mental_heath',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heartcancertext',
            name='physical_health',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
