# Generated by Django 4.0.3 on 2022-07-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0002_heartcancertext_mental_heath_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartreport',
            name='data',
        ),
    ]
